# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-14 20:15
from __future__ import unicode_literals

import accounts.fields
from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='employer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='SSN',
            field=accounts.fields.EncryptedSSNField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='employed',
            field=models.CharField(choices=[('unemp', 'Unemployed'), ('selfemp', 'Self Employed'), ('ft', 'Full Time'), ('pt', 'Part Time'), ('stu', 'Student')], default='unemp', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=localflavor.us.models.USStateField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zipCode',
            field=localflavor.us.models.USZipCodeField(),
        ),
    ]
