# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-12 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_yodleepw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='yodleepw',
        ),
    ]
