# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-06 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_middle_initial_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employment_status',
            field=models.CharField(choices=[('employed', 'Employed'), ('unemployed', 'Unemployed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='pay_frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('biweekly', 'Bi-Weekly')], max_length=20),
        ),
    ]
