# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-08 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_update_choices_to_match_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='no_of_failed_transection',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='plaid_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='questionnaire_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='repayment_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
