# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-30 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180408_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_type',
            field=models.CharField(choices=[('borrower', 'Borrower'), ('lender', 'Lender')], default='borrower', max_length=10),
        ),
    ]
