# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-04 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_plaid_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('employer_name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=20)),
                ('state', localflavor.us.models.USStateField()),
                ('zip_code', localflavor.us.models.USZipCodeField()),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='zipCode',
            new_name='zip_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='SSN',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='employed',
        ),
        migrations.AddField(
            model_name='profile',
            name='employment_status',
            field=models.CharField(choices=[('unemployed', 'Unemployed'), ('selfemployed', 'Self Employed'), ('fulltime', 'Full Time'), ('parttime', 'Part Time'), ('student', 'Student')], default='unemployed', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='license',
            field=models.FileField(blank=True, null=True, upload_to='licenses/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='paystubs',
            field=models.FileField(blank=True, null=True, upload_to='paystubs/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='M', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employment',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
