# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-05 04:22
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, help_text='0 - 5 for weighing the score.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('5'))])),
                ('textbox', models.CharField(blank=True, max_length=100, null=True)),
                ('is_alternative', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('repayment_date', models.DateField()),
                ('state', models.CharField(choices=[('rejected', 'Rejected'), ('pending', 'Pending'), ('awaiting_transfer', 'Awaiting Transfer'), ('in_repayment', 'In Repayment'), ('paid_in_full', 'Paid in Full')], default='pending', max_length=30)),
                ('plaid_score', models.SmallIntegerField(blank=True, null=True)),
                ('plaid_state', models.CharField(choices=[('failed', 'Failed'), ('no_token', 'User Not Connected'), ('pending', 'Pending'), ('success', 'Success')], default='pending', max_length=100)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('query', models.CharField(max_length=150)),
                ('score', models.DecimalField(decimal_places=2, help_text='e.g. 30 for 30%', max_digits=4)),
                ('alt_text', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textbox', models.TextField(blank=True, null=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.Choice')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='transactions.LoanRequest')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.Questionnaire'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='transactions.Question'),
        ),
    ]
