# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-15 23:20
from __future__ import unicode_literals

from decimal import Decimal as D
from django.db import migrations


Questions_Choices = [
    dict(
        query='What will the majority of the funds be used for?', score=D(15),
        choices=[
            dict(option='Food, Water, Shelter', weight=D(5)),
            dict(option='Bill payments (electric, phone, cable, car, etc.)', weight=D(4)),
            dict(option='Friends or Family', weight=D(3)),
            dict(option='Special Event', weight=D(2)),
        ]
    ),
    dict(
        query='Do you rent or own your home?', score=D(10),
        choices=[
            dict(option='Own', weight=D(5), textbox='Enter mortgage holder'),
            dict(option='Rent', weight=D(4)),
        ]
    ),
    dict(
        query='How many times have you applied for credit over the past year?', score=D(10),
        choices=[
            dict(option='0 - 1 times', weight=D(5)),
            dict(option='1 - 3 times', weight=D(2.5)),
            dict(option='3 - 6 times', weight=D(0)),
            dict(option='6 - 9 times', weight=D(0)),
        ],
    ),
    dict(
        query='How many times have you checked your credit score over the past year?', score=D(10),
        choices=[
            dict(option='4 or more times', weight=D(5)),
            dict(option='2 or 3 times', weight=D(2.5)),
            dict(option='1 time', weight=D(1.5)),
            dict(option='0 times', weight=D(0)),
        ]
    ),
    dict(
        query='How long have you worked in the industry you’re currently in?', score=D(25),
        alt_text='Not Applicable',
        choices=[
            dict(option='0 - 3 months', weight=D(1)),
            dict(option='4 - 12 months', weight=D(2)),
            dict(option='1 - 3 years', weight=D(3)),
            dict(option='3 - 6 years', weight=D(4)),
            dict(option='6 - 10 years or beyond', weight=D(5)),

            dict(option='0 - 3 months', weight=D(1), is_alternative=True),
            dict(option='4 - 12 months', weight=D(2), is_alternative=True),
            dict(option='1 - 3 years', weight=D(3), is_alternative=True),
            dict(option='3 - 6 years', weight=D(4), is_alternative=True),
            dict(option='6 - 10 years or beyond', weight=D(5), is_alternative=True),
        ]
    ),
    dict(
        query='What’s your highest level of education completed?', score=D(30),
        choices=[
            dict(option='Some high school (no diploma)', weight=D(1)),
            dict(option='High school diploma or GED', weight=D(2)),
            dict(option='Some community college', weight=D(2.5)),
            dict(option='Associates degree', weight=D(3)),
            dict(option='Bachelor’s degree', weight=D(4)),
            dict(option='Graduate degree', weight=D(5)),
        ]
    ),
]


def make_questionnaire(apps, schema):
    Questionnaire = apps.get_model('transactions', 'Questionnaire')
    Question = apps.get_model('transactions', 'Question')
    Choice = apps.get_model('transactions', 'Choice')

    qa = Questionnaire.objects.create()
    for question_choice in Questions_Choices:
        choices = question_choice.pop('choices')
        que = Question.objects.create(questionnaire=qa, **question_choice)
        for choice in choices:
            Choice.objects.create(question=que, **choice)


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(make_questionnaire)
    ]
