# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-16 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rip_out_yodlee'),
        ('transactions', '0002_add_hardcoded_questionnaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('state', models.CharField(choices=[('rejected', 'rejected'), ('pending', 'pending'), ('awaiting_transfer', 'awaiting_transfer'), ('in_repayment', 'in_repayment'), ('paid_in_full', 'paid_in_full')], default='pending', max_length=30)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textbox', models.TextField(blank=True, null=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.Choice')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='transactions.LoanRequest')),
            ],
        ),
    ]
