# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-24 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_add_hardcoded_questionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_transfer', 'Awaiting Transfer'), ('in_repayment', 'In Repayment'), ('paid_in_full', 'Paid in Full')], default='pending', max_length=30),
        ),
    ]
