# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-20 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_add_plaid_fields_to_loan_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='plaid_state',
            field=models.CharField(choices=[('failed', 'Failed'), ('no_token', 'User Not Connected'), ('pending', 'Pending'), ('success', 'Success')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='state',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('pending', 'Pending'), ('awaiting_transfer', 'Awaiting Transfer'), ('in_repayment', 'In Repayment'), ('paid_in_full', 'Paid in Full')], default='pending', max_length=30),
        ),
    ]
