# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-20 03:39
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_adjust_state_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='0 - 5 for weighing the score.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('5'))]),
        ),
    ]
