# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-01 19:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_fix_validation_and_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='repayment_date',
            field=models.DateField(default=datetime.date(2016, 10, 1)),
            preserve_default=False,
        ),
    ]
